services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "80:80"
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  apigateway:
    image: apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - consul
  web:
    image: web
    container_name: backweb
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq
  web2:
    image: web
    container_name: backweb2
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq
  web3:
    image: web
    container_name: backweb3
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq
  empresa:
    image: empresa
    container_name: empresaweb
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq
  empresa2:
    image: empresa
    container_name: empresaweb2
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq
  empresa3:
    image: empresa
    container_name: empresaweb3
    depends_on:
      - db
      - consul
      - apigateway
      - rabbitmq


