services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'virtualtravelweb'
  db2:
    image: mysql
    container_name: db2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'virtualtravelempresa'
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "81:80"
  phpmyadmin2:
    image: phpmyadmin
    container_name: pma2
    links:
      - db2
    environment:
      PMA_HOST: db2
      PMA_PORT: 3306
    ports:
      - "82:80"
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  appgateway:
    image: skhalilov/khalilovgateway
    container_name: khalilovagateway
    ports:
      - "8080:8080"
    depends_on:
      - consul
  khalilovempresa1:
    image: skhalilov/khalilovempresa
    container_name: khalilovempresa1
    depends_on:
      - db2
      - consul
      - rabbitmq
  khalilovempresa2:
    image: skhalilov/khalilovempresa
    container_name: khalilovempresa2
    depends_on:
      - db2
      - consul
      - rabbitmq
  khalilovweb:
    image: skhalilov/khalilovweb
    container_name: khalilovweb
    depends_on:
      - db
      - consul
      - rabbitmq
  khalilovweb2:
    image: skhalilov/khalilovweb
    container_name: khalilovweb2
    depends_on:
      - db
      - consul
      - rabbitmq