

spring:
  application:
    name: apigateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        health-check-path: /
server:
  port: 8080