

spring:
  application:
    name: apigateway
  cloud:
#    gateway:
#      routes:
#        - id: backweb
#          uri: lb://BACKWEB/
#          predicates:
#            - Path=/api/v1/web/**
#          filters:
#            - RewritePath=/api/v1/web/(?<segment>/?.*), /api/$\{segment}
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instance-id: "${spring.application.name}-${server.port}-${spring.cloud.client.ip-address}"
        health-check-path: /
server:
  port: 8080